MODEL:
  BACKBONE: ResNet50
  CROSS_ATTENTION_TYPE: hard_masked
  NUM_BACKGROUND_QUERIES: 1
  NUM_OBJECT_QUERIES: 128
  NUM_VOS_QUERIES_PER_OBJECT: 4
TRAINING:
  BATCH_SIZE: 32
  CLIP_LENGTH: 3
  DATASET_LIST:
  - COCO
  - ADE20K
  - CITYSCAPES
  - MAPILLARY
  DATASET_WEIGHTS:
  - 0.55
  - 0.2
  - 0.05
  - 0.2
  LOSSES:
    PANOPTIC_SEMANTIC_WEIGHT_CROSS_ENTROPY: 2.0
  LR_DECAY_RATES:
  - 0.1
  - 0.1
  LR_DECAY_STEPS:
  - 444500
  - 481500
  NUM_ITERATIONS: 500000
  NUM_SAMPLED_POINTS_FOR_MASK_LOSS: 12544
  POINT_VOS_TASK_SAMPLE_LIKELIHOOD: 0.3
  PRETRAINING: true
  PRETRAIN_IMAGE_SIZE:
  - 512
  - 512
  PRETRAIN_TASK_WEIGHTS:
    INSTANCE_SEG: 0.0
    PANOPTIC_SEG: 0.0
    VOS: 1.0
  SAMPLE_CHUNKING_FACTOR: 8
