DATASETS:
  ADE20K:
    NUM_CLASSES: 150
    TYPE: panoptic_seg
  BURST:
    INFERENCE:
      CLIP_LENGTH: 8
      FRAME_OVERLAP: 4
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS:
        - 512
        MODE: min_dim
      MODE: point
      SPLIT: val
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 3.0
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS:
        - 512
        MODE: min_dim
    TYPE: vos
  CITYSCAPES:
    NUM_CLASSES: 34
    TYPE: panoptic_seg
  CITYSCAPES_VPS:
    INFERENCE:
      CLIP_LENGTH: 10
      FRAME_OVERLAP: 5
      IMAGE_RESIZE:
        MAX_DIM: 2048
        MIN_DIMS: 736
        MODE: none
      MAX_TRACKS_PER_CLIP: 1000
      POSTPROCESS_ON_CPU: false
      SPARSE_FRAMES: true
      TRACK_SCORE_THRESHOLD: 0.5
    NUM_CLASSES: 19
    SHARED_SEMSEG_QUERIES: false
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 1.0
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS:
        - 448
        MODE: min_dim
      SPLIT: train
    TYPE: panoptic_seg
  COCO:
    NUM_CLASSES: 133
    TYPE: panoptic_seg
  DAVIS:
    INFERENCE:
      CLIP_LENGTH: 12
      FRAME_OVERLAP: 6
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS:
        - 360
        MODE: none
      SPLIT: val
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 20.0
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS:
        - 480
        MODE: min_dim
    TYPE: vos
  KITTI_STEP:
    INFERENCE:
      CLIP_LENGTH: 6
      FRAME_OVERLAP: 3
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS: 240
        MODE: none
      MAX_TRACKS_PER_CLIP: 1000
      TRACK_SCORE_THRESHOLD: 0.5
    NUM_CLASSES: 19
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 3.0
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS:
        - 320
        MODE: min_dim
      SPLIT: train
    TYPE: panoptic_seg
  MAPILLARY:
    NUM_CLASSES: 65
    TYPE: panoptic_seg
  OVIS:
    INFERENCE:
      CLIP_LENGTH: 12
      FRAME_OVERLAP: 6
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS: 360
        MODE: min_dim
        TARGET_PIXEL_AREA: 300000
      MAX_TRACKS_PER_CLIP: 10
      TRACK_SCORE_THRESHOLD: 0.0
    NUM_CLASSES: 25
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 10.0
      IMAGE_RESIZE:
        MAX_DIM: 1024
        MIN_DIMS:
        - 360
        - 480
        MODE: min_dim
    TYPE: instance_seg
  VIPSEG:
    INFERENCE:
      CLIP_LENGTH: 12
      FRAME_OVERLAP: 6
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS: 576
        MODE: min_dim
      MAX_TRACKS_PER_CLIP: 1000
      POSTPROCESS_ON_CPU: false
      TRACK_SCORE_THRESHOLD: 0.5
      SPLIT: val
    NUM_CLASSES: 124
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 5.0
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS:
        - 512
        MODE: min_dim
    TYPE: panoptic_seg
  YOUTUBE_VIS:
    INFERENCE:
      CLIP_LENGTH: 12
      FRAME_OVERLAP: 6
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS: 360
        MODE: min_dim
        TARGET_PIXEL_AREA: 300000
      MAX_TRACKS_PER_CLIP: 10
      TRACK_SCORE_THRESHOLD: 0.0
    NUM_CLASSES: 40
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 10.0
      IMAGE_RESIZE:
        MAX_DIM: 1024
        MIN_DIMS:
        - 360
        - 480
        MODE: min_dim
    TYPE: instance_seg
INPUT:
  NORMALIZE_TO_UNIT_SCALE: false
  PIXEL_MEAN:
  - 103.53
  - 116.28
  - 123.675
  PIXEL_STD:
  - 57.375
  - 57.12
  - 58.395
  RGB: true
MODEL:
  BACKBONE: ResNet50
  CROSS_ATTENTION_TYPE: hard_masked
  NUM_BACKGROUND_QUERIES: 1
  NUM_OBJECT_QUERIES: 100
  NUM_VOS_QUERIES_PER_OBJECT: 1
TRAINING:
  ACCUMULATE_GRADIENTS: true
  BASE_LR: 0.0001
  BATCH_SIZE: 8
  CHECKPOINT_SAVE_INTERVAL: 20000
  CLIP_LENGTH: 3
  DATASET_LIST:
  - COCO
  DATASET_WEIGHTS:
  - 1.0
  LOSSES:
    INSTANCE_SEMANTIC_WEIGHT_CROSS_ENTROPY: 2.0
    PANOPTIC_INSTANCE_NUM_POINTS: 12544
    PANOPTIC_SEMANTIC: sparse
    PANOPTIC_SEMANTIC_NUM_POINTS: 25088
    PANOPTIC_SEMANTIC_WEIGHT_CROSS_ENTROPY: 2.0
    PANOPTIC_SEMANTIC_WEIGHT_DICE: 0.0
    SEMANTIC_IGNORE_NULL_CLASSES: false
    SEMANTIC_REGULARIZATION_LOSS: false
  LR_DECAY_RATES:
  - 0.0
  LR_DECAY_STEPS:
  - 0
  LR_WARMUP_ITERATIONS: 0
  NUM_ITERATIONS: 0
  NUM_SAMPLED_POINTS_FOR_MASK_LOSS: 12544
  POINT_VOS_TASK_SAMPLE_LIKELIHOOD: 0.3
  PRETRAINING: false
  PRETRAIN_AUGMENTATION_TYPE: crop
  PRETRAIN_IMAGE_SIZE:
  - 512
  - 512
  PRETRAIN_TASK_WEIGHTS:
    INSTANCE_SEG: 0.3
    PANOPTIC_SEG: 0.3
    VOS: 0.4
  SAMPLE_CHUNKING_FACTOR: 8
