TRAINING:
  PRETRAINING: False
  CLIP_LENGTH: 3
  BATCH_SIZE: 32
  NUM_ITERATIONS: 90000 # 50000
  LR_DECAY_STEPS: [50000, 84000] # [17500, 30000]
  LR_DECAY_RATES: [0.1, 0.1]
  DATASET_LIST: ["YOUTUBE_VIS", "OVIS", "KITTI_STEP", "CITYSCAPES_VPS", "VIPSEG", "BURST", "DAVIS"]
  DATASET_WEIGHTS: [0.225, 0.225, 0.075, 0.075, 0.15, 0.2, 0.05]
  # DATASET_LIST: ["YOUTUBE_VIS", "OVIS", "KITTI_STEP", "CITYSCAPES_VPS", "VIPSEG", "BURST", "DAVIS"]
  # DATASET_WEIGHTS: [0.01, 0.01, 0.01, 0.01, 0.94, 0.01, 0.01]
  NUM_SAMPLED_POINTS_FOR_MASK_LOSS: 12544
  CHECKPOINT_SAVE_INTERVAL: 10000
  LR_WARMUP_ITERATIONS: 10000
  SAMPLE_CHUNKING_FACTOR: 8
  LOSSES:
    PANOPTIC_SEMANTIC: "sparse"
    PANOPTIC_INSTANCE_NUM_POINTS: 12544
    PANOPTIC_SEMANTIC_NUM_POINTS: 50176
    PANOPTIC_SEMANTIC_WEIGHT_CROSS_ENTROPY: 2.0
    PANOPTIC_SEMANTIC_WEIGHT_DICE: 0.0
DATASETS:
  YOUTUBE_VIS:
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 7.5 # 10.0
      IMAGE_RESIZE:
        MODE: "min_dim"
        MIN_DIMS: [448, 512] # [360, 480]
        MAX_DIM: 1024
    INFERENCE:
      CLIP_LENGTH: 12
      FRAME_OVERLAP: 6
      IMAGE_RESIZE:
        MODE: "min_dim"
        MIN_DIMS: 448
  OVIS:
    TYPE: "instance_seg"
    NUM_CLASSES: 25
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 7.5 # 10.0
      IMAGE_RESIZE:
        MODE: "min_dim"
        MIN_DIMS: [512] # [360, 480]
        MAX_DIM: 1024
    INFERENCE:
      CLIP_LENGTH: 12
      FRAME_OVERLAP: 6
      IMAGE_RESIZE:
        MODE: "min_dim"
        TARGET_PIXEL_AREA: 300000
        MIN_DIMS: 576
        MAX_DIM: 1333
  DAVIS:
    TYPE: "vos"
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 7.5 # 10.0
      IMAGE_RESIZE:
        MODE: "min_dim"
        MIN_DIMS: [512] # [480]
        MAX_DIM: 1333
    INFERENCE:
      CLIP_LENGTH: 12
      FRAME_OVERLAP: 6
      IMAGE_RESIZE:
        MODE: "none"
  KITTI_STEP:
    TYPE: "panoptic_seg"
    TRAINING:
      SPLIT: "train"
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 2.0
      IMAGE_RESIZE:
        MODE: "min_dim"
        MIN_DIMS: [320]
        MAX_DIM: 1333
    INFERENCE:
      CLIP_LENGTH: 6
      FRAME_OVERLAP: 3
      MAX_TRACKS_PER_CLIP: 1000
      TRACK_SCORE_THRESHOLD: 0.5
      IMAGE_RESIZE:
        MODE: "none"
        MIN_DIMS: 240
        MAX_DIM: 1333
  CITYSCAPES_VPS:
    SHARED_SEMSEG_QUERIES: False
  VIPSEG:
    TYPE: "panoptic_seg"
    NUM_CLASSES: 124
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 5.0
      IMAGE_RESIZE:
        MODE: "min_dim"
        MIN_DIMS: [512]
        MAX_DIM: 1333