DATASETS:
  CITYSCAPES_VPS:
    SHARED_SEMSEG_QUERIES: false
  DAVIS:
    INFERENCE:
      CLIP_LENGTH: 12
      FRAME_OVERLAP: 6
      IMAGE_RESIZE:
        MODE: none
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 7.5
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS:
        - 512
        MODE: min_dim
    TYPE: vos
  KITTI_STEP:
    INFERENCE:
      CLIP_LENGTH: 6
      FRAME_OVERLAP: 3
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS: 240
        MODE: none
      MAX_TRACKS_PER_CLIP: 1000
      TRACK_SCORE_THRESHOLD: 0.5
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 2.0
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS:
        - 320
        MODE: min_dim
      SPLIT: train
    TYPE: panoptic_seg
  OVIS:
    INFERENCE:
      CLIP_LENGTH: 12
      FRAME_OVERLAP: 6
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS: 576
        MODE: min_dim
        TARGET_PIXEL_AREA: 300000
    NUM_CLASSES: 25
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 7.5
      IMAGE_RESIZE:
        MAX_DIM: 1024
        MIN_DIMS:
        - 512
        MODE: min_dim
    TYPE: instance_seg
  VIPSEG:
    NUM_CLASSES: 124
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 5.0
      IMAGE_RESIZE:
        MAX_DIM: 1333
        MIN_DIMS:
        - 512
        MODE: min_dim
    TYPE: panoptic_seg
  YOUTUBE_VIS:
    INFERENCE:
      CLIP_LENGTH: 12
      FRAME_OVERLAP: 6
      IMAGE_RESIZE:
        MIN_DIMS: 448
        MODE: min_dim
    TRAINING:
      FRAME_SAMPLING_MULTIPLICATIVE_FACTOR: 7.5
      IMAGE_RESIZE:
        MAX_DIM: 1024
        MIN_DIMS:
        - 448
        - 512
        MODE: min_dim
TRAINING:
  BATCH_SIZE: 32
  CHECKPOINT_SAVE_INTERVAL: 10000
  CLIP_LENGTH: 3
  DATASET_LIST:
  - YOUTUBE_VIS
  - OVIS
  - KITTI_STEP
  - CITYSCAPES_VPS
  - VIPSEG
  - BURST
  - DAVIS
  DATASET_WEIGHTS:
  - 0.225
  - 0.225
  - 0.075
  - 0.075
  - 0.15
  - 0.2
  - 0.05
  LOSSES:
    INSTANCE_SEMANTIC_WEIGHT_CROSS_ENTROPY: 1.0
    PANOPTIC_INSTANCE_NUM_POINTS: 12544
    PANOPTIC_SEMANTIC: sparse
    PANOPTIC_SEMANTIC_NUM_POINTS: 50176
    PANOPTIC_SEMANTIC_WEIGHT_CROSS_ENTROPY: 1.0
    PANOPTIC_SEMANTIC_WEIGHT_DICE: 0.0
    SEMANTIC_IGNORE_NULL_CLASSES: false
    SEMANTIC_REGULARIZATION_LOSS: true
  LR_DECAY_RATES:
  - 0.1
  - 0.1
  LR_DECAY_STEPS:
  - 50000
  - 84000
  LR_WARMUP_ITERATIONS: 10000
  NUM_ITERATIONS: 90000
  NUM_SAMPLED_POINTS_FOR_MASK_LOSS: 12544
  PRETRAINING: false
  SAMPLE_CHUNKING_FACTOR: 8
